# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g7feedbackmodel',
            name='context',
            field=models.TextField(default='', max_length=2000, verbose_name='反馈内容'),
        ),
    ]
