# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='G7FeedbackModel',
        ),
    ]
