# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_g7feedbackmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='G7FeedbackModel',
        ),
    ]
