# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0005_g7feedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='g7feedbackmodel',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='', verbose_name='反馈图片'),
        ),
    ]
