# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-19 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='测试姓名')),
                ('contact', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='测试联系方式')),
            ],
        ),
    ]
